version: '3'
services:
  mysql:
    image: mysql:8.0.20
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 13306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  login-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-login-api/build/libs:/home/eatgo/libs
    ports:
      - 8001:8181
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
  admin-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-admin-api/build/libs:/home/eatgo/libs
    ports:
      - 8002:8181
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
  customer-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-customer-api/build/libs:/home/eatgo/libs
    ports:
      - 8003:8181
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"
  restaurant-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/eatgo/run.sh
      - ./eatgo-restaurant-api/build/libs:/home/eatgo/libs
    ports:
      - 8004:8181
    depends_on:
      - mysql
    command: bash -c "cd /home/eatgo && sh run.sh"