version: '3'
services:
  mysql-standalone:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eatgo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  eatgo-customer-api:
    image: eatgo-customer-api:1.0.0
    ports:
      - 8080:8080
    build:
      context: ./eatgo-customer-api
      args:
        ENVIRONMENT: prod
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone

  eatgo-login-api:
    image: eatgo-login-api:1.0.0
    ports:
      - 8081:8080
    build:
      context: ./eatgo-login-api
      args:
        ENVIRONMENT: prod
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone

  eatgo-restaurant-api:
    image: eatgo-restaurant-api:1.0.0
    ports:
      - 8082:8080
    build:
      context: ./eatgo-restaurant-api
      args:
        ENVIRONMENT: prod
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone

  eatgo-admin-api:
    image: eatgo-admin-api:1.0.0
    ports:
      - 8083:8080
    build:
      context: ./eatgo-admin-api
      args:
        ENVIRONMENT: prod
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
